language: ruby
rvm:
- 2.7.3
cache: bundler

# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild

# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild

# only run CI-builds on master branch
branches:
  only:
  - main

exclude: [vendor]
sudo: false
